//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RanEditSkinPiece.rc
//
#define ID_ADDCOLOUR                    3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DLG_MAIN                    101
#define IDR_MAINFRAME                   128
#define IDR_RanEditSkinPiecTYPE         129
#define IDD_COLSEL                      129
#define IDD_DIALOG_MAIN                 130
#define IDD_DLG_EFF                     131
#define IDD_DLG_EFF_SINGLE              132
#define IDC_DRAGITEM                    132
#define IDD_DLG_EFF_BLUR                133
#define IDC_EDIT_FILENAME               1000
#define IDC_EDIT_SKIN                   1001
#define IDC_NEWVERSION                  1001
#define IDC_EDIT_SKELETON               1002
#define IDC_COMBO_PIECE_TYPE            1003
#define IDC_HUE                         1003
#define IDC_BUTTON_SETMESH              1004
#define IDC_SAT                         1004
#define IDC_BUTTON_FINDSKIN             1005
#define IDC_LUM                         1005
#define IDC_BUTTON_FINDSKELETON         1006
#define IDC_RED                         1006
#define IDC_BUTTON_PAGESEL              1007
#define IDC_BUTTON_SETSKINSKELETON      1007
#define IDC_GREEN                       1007
#define IDC_COMBO_WEAPONWHEREBACK       1008
#define IDC_BLUE                        1008
#define IDC_BUTTON_TRACE_ADD            1009
#define IDC_BUTTON_TRACE_DEL            1010
#define IDC_BUTTON_EFF_ADD              1011
#define IDC_BUTTON_EFF_DEL              1012
#define IDC_REF                         1012
#define IDC_BUTTON_EFF_EDIT             1013
#define IDC_EDIT_MESHNAME               1014
#define IDC_EDIT_MATERIAL_TEXTURE       1015
#define IDC_COMBO_MATERIAL_BIAS         1016
#define IDC_BUTTON_MATERIAL_SIZE        1017
#define IDC_BUTTON_DLGEFF_SAVE          1018
#define IDC_COMBO_EFF                   1018
#define IDC_BUTTON_DLGEFF_CANCEL        1019
#define IDC_BUTTON_EFF_OK               1019
#define IDC_BUTTON_DLGEFF_APPLY         1020
#define IDC_BUTTON_FILENAME             1022
#define IDC_EDIT_MOVEPOS_1              1025
#define IDC_EDIT_MOVEPOS_2              1027
#define IDC_CHECK_1DOT                  1029
#define IDC_CHECK_2DOTS                 1030
#define IDC_CHECK_MATRIX                1031
#define IDC_EDIT_SCALE                  1032
#define IDC_CHECK_AUTOMOVE              1033
#define IDC_CHECK_REPEATMOVE            1034
#define IDC_EDIT_REPEATSPEED            1035
#define IDC_CHECK_REPEAT                1036
#define IDC_EDIT_COOLDOWN               1037
#define IDC_COMBO_ANISET                1038
#define IDC_COMBO_WEATHERSET            1039
#define IDC_LIST_DOT1                   1040
#define IDC_EDIT_TRACE1                 1041
#define IDC_LIST_DOT2                   1042
#define IDC_EDIT_TRACE2                 1043
#define IDC_COMBO_BLEND                 1044
#define IDC_CHECK_USE_REFRACT           1045
#define IDC_CHECK_USE_ALLACTION         1046
#define IDC_EDIT_ALPHA_1                1047
#define IDC_EDIT_ALPHA_2                1048
#define IDC_EDIT_ALPHA_COLOR_1_R        1049
#define IDC_EDIT_ALPHA_COLOR_1_G        1050
#define IDC_EDIT_ALPHA_COLOR_1_B        1051
#define IDC_EDIT_ALPHA_COLOR_2_R        1052
#define IDC_EDIT_ALPHA_COLOR_2_G        1053
#define IDC_EDIT_ALPHA_COLOR_2_B        1054
#define IDC_BUTTON_COLOR1               1055
#define IDC_BUTTON_COLOR2               1056
#define IDC_CHECK_USE_BEZIER            1057
#define IDC_EDIT_FACES                  1058
#define IDC_EDIT_WIDTH                  1059
#define IDC_EDIT_COLOR_A_1              1060
#define IDC_EDIT_COLOR_R_1              1061
#define IDC_EDIT_COLORS_A_2             1061
#define IDC_EDIT_COLOR_G_1              1062
#define IDC_EDIT_COLOR_B_1              1063
#define IDC_BUTTON_COLOR                1064
#define IDC_EDIT_FULLTIME               1065
#define IDC_EDIT_LENGTH                 1066
#define IDC_CHECK_GRAVITY               1067
#define IDC_EDIT_GRAVITY                1068
#define IDC_CHECK_FLARE                 1069
#define IDC_EDIT_FLARE                  1070
#define IDC_EDIT_RAND                   1071
#define IDC_EDIT_BLUR                   1072
#define IDC_EDIT_EFF1                   1072
#define IDC_EDIT_EFF2                   1073
#define IDC_BUTTON_EFF1                 1074
#define IDC_BUTTON_EFF2                 1075
#define IDC_CHECK_USE_EFF               1076
#define IDC_CHECK_USE_SEC               1078
#define IDC_EDIT_SEC                    1079
#define IDC_CHECK_USE_ARROW             1080
#define IDC_CHECK_USE_SIZE              1081
#define IDC_EDIT_SIZE                   1082
#define IDC_CHECK_USE_RANDOM            1084
#define IDC_EDIT_ALPHA                  1085
#define IDC_EDIT_SET                    1086
#define IDC_EDIT_DEPTH                  1087
#define IDC_EDIT_COLOR_A                1088
#define IDC_EDIT_COLOR_R                1089
#define IDC_EDIT_COLOR_G                1090
#define IDC_EDIT_COLOR_B                1091
#define IDC_EDIT_MESH                   1093
#define IDC_BUTTON_MESH                 1094
#define IDC_CHECK_SPECULAR              1095
#define IDC_BUTTON_SPECULAR             1096
#define IDC_EDIT_SPECULAR               1097
#define IDC_BUTTON_SPECULAR_OK          1098
#define IDC_LIST_SPECULAR               1099
#define IDC_COMBO_COLOR_OP              1100
#define IDC_EDIT_SPECULAR_POWER         1100
#define IDC_COMBO_COLOR_OP2             1101
#define IDC_EDIT_POWER                  1103
#define IDC_CHECK_USE_TRANSLUCENT       1104
#define IDC_EDIT_PLAYTIME               1106
#define IDC_EDIT_WAITTIME               1107
#define IDC_CHECK_GLOW_DEF              1107
#define IDC_CHECK_GLOW_BURN             1108
#define IDC_CHECK_TEXTURE_ALL           1109
#define IDC_CHECK_TEXTURE_SELECTION     1110
#define IDC_CHECK_COLOR_SOURCE          1111
#define IDC_CHECK_COLOR_SOURCE2         1112
#define IDC_BUTTON_TEXT                 1113
#define IDC_EDIT_TEX                    1114
#define IDC_CHECK_USE1                  1115
#define IDC_CHECK_USE2                  1116
#define IDC_EDIT_TEX1                   1117
#define IDC_EDIT_TEX2                   1118
#define IDC_BUTTON_TEX1                 1119
#define IDC_BUTTON_TEX2                 1120
#define IDC_LIST_TRACE                  1123
#define IDC_EDIT_COLORS_R_1             1123
#define IDC_LIST_EFF                    1124
#define IDC_EDIT_COLORS_A_1             1124
#define IDC_LIST_MESH                   1125
#define IDC_EDIT_COLORS_R_2             1125
#define IDC_LIST_MATERIAL               1126
#define IDC_EDIT_COLORS_G_1             1126
#define IDC_EDIT_COLORS_G_2             1127
#define IDC_EDIT_COLORS_B_1             1128
#define IDC_EDIT_COLORS_B_2             1129
#define IDC_EDIT_VTEX_X_1               1130
#define IDC_EDIT_VTEX_X_2               1131
#define IDC_EDIT_VTEX_Y_1               1132
#define IDC_EDIT_VTEX_Y_2               1133
#define IDC_EDIT_VTEXUV_X_1             1134
#define IDC_EDIT_VTEXUV_X_2             1135
#define IDC_EDIT_VTEXUV_Y_1             1136
#define IDC_EDIT_VTEXUV_Y_2             1137
#define IDC_BUTTON_TEXTURE              1137
#define IDC_EDIT_TEXTURE                1138
#define IDC_EDIT_SPECULARPOWER          1139
#define IDC_BUTTON_TEXTURE_1            1139
#define IDC_EDIT_TEXTURE_OBLI           1139
#define IDC_CHECK_ALLTIME               1140
#define IDC_BUTTON_TEXTURE_2            1140
#define IDC_BUTTON_TEXTURE_3            1141
#define IDC_EDIT_TIME                   1142
#define IDC_CHECK_TEXCOLOR              1143
#define IDC_EDIT_AMBIENT_A              1146
#define IDC_EDIT_AMBIENT_R              1147
#define IDC_CHECK_USE_TEX_1             1147
#define IDC_EDIT_AMBIENT_G              1148
#define IDC_CHECK_USE_TEX_2             1148
#define IDC_EDIT_AMBIENT_B              1149
#define IDC_CHECK_USE_TEX_3             1149
#define IDC_COMBO_DETAIL_1              1150
#define IDC_COMBO_DETAIL_2              1151
#define IDC_COMBO_DETAIL_3              1152
#define IDC_COMBO_COLOROP               1153
#define IDC_EDIT_SRC_TEX1               1154
#define IDC_EDIT_SRC_TEX2               1155
#define IDC_EDIT_SRC_TEX3               1156
#define IDC_EDIT_TEXTURE_1              1157
#define IDC_EDIT_TEXTURE_2              1158
#define IDC_EDIT_TEXTURE_3              1159
#define IDC_EDIT_DOTTEXTURE_1           1160
#define IDC_EDIT_DOTTEXTURE_2           1161
#define IDC_EDIT_DOTTEXTURE_3           1162
#define IDC_BUTTON_SRC_TEX_1            1164
#define IDC_BUTTON_SRC_TEX_2            1165
#define IDC_BUTTON_SRC_TEX_3            1166
#define IDC_BUTTON_DOT_TEXTURE_1        1167
#define IDC_BUTTON_DOT_TEXTURE_2        1168
#define IDC_CHECK_ALL_TEX               1168
#define IDC_BUTTON_DOT_TEXTURE_3        1169
#define IDC_CHECK_LIST_TEX              1169
#define IDC_CHECK_USE_TEX1              1170
#define IDC_CHECK_USE_TEX2              1171
#define IDC_BUTTON_TEX_1                1172
#define IDC_BUTTON_TEX_2                1173
#define IDC_EDIT_TEX_1                  1174
#define IDC_EDIT_TEX_2                  1175
#define IDC_BUTTON_TEXMAP               1176
#define IDC_EDIT_TEXMAP                 1177
#define IDC_CHECK_USE_TEXMAP            1178
#define IDC_COMBO_ANI_MAIN              1178
#define IDC_COMBO_ANI_SUB               1179
#define IDC_EDIT_GNUM                   1182
#define IDC_EDIT_UNIT                   1183
#define IDC_CHECK_CUBEMAP               1185
#define IDC_EDITS_SIZE                  1186
#define IDC_EDITS_SIZEADD               1187
#define IDC_BUTTON_OBLI                 1190
#define IDC_CHECK_OBLI                  1191
#define IDC_CHECK_UPDOWN                1192
#define IDC_EDIT_SPEED                  1193
#define IDC_COMBO_INTEN                 1194
#define IDC_EDIT_PEC                    1195
#define IDC_EDIT_RANDOMRANGE            1196
#define IDC_CHECK_RANDOMRANGE           1197
#define IDC_EDIT_LIFEMIN                1198
#define IDC_EDIT_LIFEMAX                1199
#define IDC_EDIT_SCALE_X                1200
#define IDC_EDIT_SCALE_Y                1201
#define IDC_EDIT_SCALE_Z                1202
#define IDC_EDIT_ROTATE_MIN             1203
#define IDC_EDIT_ROTATE_MAX             1204
#define IDC_CHECK_ROTATE                1205
#define IDC_EDIT_SEQ_COL                1206
#define IDC_EDIT_SEQ_ROW                1207
#define IDC_CHECK_SEQ                   1208
#define IDC_CHECK_REMAIN                1209
#define IDC_CHECK_OFFLEVEL              1209
#define IDC_EDIT_VEL_MIN                1210
#define IDC_EDIT_VEL_MAX                1211
#define IDC_LIST_POS                    1216
#define IDC_BUTTON_POS_ADD              1217
#define IDC_BUTTON_POS_DEL              1218
#define IDC_EDIT_VEL_X                  1218
#define IDC_BUTTON_POS_UP               1219
#define IDC_EDIT_VEL_Z                  1219
#define IDC_BUTTON_POS_DOWN             1220
#define IDC_EDIT_VEL_Y                  1220
#define IDC_EDIT_CREATELENGTH           1221
#define IDC_BUTTON_BONE_SELECT          1222
#define IDC_EDIT_BONE                   1223
#define IDC_EDIT_LOCAL_X                1224
#define IDC_EDIT_LOCAL_Y                1225
#define IDC_EDIT_LOCAL_Z                1226
#define IDC_CHECK_OFFSET                1228
#define IDC_CHECK_USE_REMAIN            1229
#define IDC_BUTTON_GET_FROM_SCREEN      1231
#define IDC_BUTTON_BONE_ADD             1232
#define IDC_BUTTON_BONE_EDIT            1233
#define IDC_BUTTON_BONE_UP              1234
#define IDC_BUTTON_BONE_DOWN            1235
#define IDC_BUTTON_DEL                  1236
#define IDC_CHECK_MOVE                  1237
#define IDC_EDIT_OFFSET_X               1238
#define IDC_EDIT_OFFSET_Y               1239
#define IDC_EDIT_OFFSET_Z               1240
#define IDC_BUTTON_SCREENPOS            1241
#define IDC_BUTTON_POS_SAVE             1242
#define IDC_EDIT_SHAKE                  1245
#define IDC_EDIT_LIFE_X                 1246
#define IDC_EDIT_LIFE_Y                 1247
#define IDC_EDIT_SIZE_X                 1248
#define IDC_EDIT_SIZE_Y                 1249
#define IDC_EDIT_SIZE_Z                 1250
#define IDC_EDIT_SEC_COL                1251
#define IDC_EDIT_SEC_ROW                1252
#define IDC_EDIT_X_SCALE_X              1254
#define IDC_EDIT_X_SCALE_Y              1255
#define IDC_EDIT_Y_SCALE_X              1256
#define IDC_EDIT_Y_SCALE_Y              1257
#define IDC_EDIT_Y_SCALE_Z              1258
#define IDC_BUTTON_COLOR_1              1259
#define IDC_BUTTON_COLOR_2              1260
#define IDC_CHECK_CAM_MOVE              1261
#define IDC_COMBO_OTHER                 1262
#define IDC_BUTTON_INSERT               1263
#define IDC_BUTTON_DELETE               1264
#define IDC_EDIT_BONE_1                 1265
#define IDC_EDIT_BONE_2                 1266
#define IDC_BUTTON_BONE_1               1267
#define IDC_BUTTON_BONE_2               1268
#define IDC_EDIT_REPLAY_X               1273
#define IDC_EDIT_REPLAY_Y               1274
#define IDC_EDIT_XSIZE_X                1275
#define IDC_EDIT_XSIZE_Y                1276
#define IDC_EDIT_YSIZE_X                1277
#define IDC_EDIT_YSIZE_Y                1278
#define IDC_EDIT_SPEED_MIN              1279
#define IDC_EDIT_SPEED_MAX              1280
#define IDC_EDIT_COLORS_A               1284
#define IDC_EDIT_COLORS_R               1285
#define IDC_EDIT_COLORS_G               1286
#define IDC_EDIT_COLORS_B               1287
#define IDC_BUTTON_TEX                  1289
#define IDC_EDIT_GET_X                  1292
#define IDC_EDIT_GET_Y                  1293
#define IDC_EDIT_GET_Z                  1294
#define IDC_EDIT_DIST                   1295
#define IDC_BUTTON_GET                  1296
#define IDC_BUTTON_MAT_EDIT             1298
#define IDC_BUTTON_MAT_EDIT2            1299
#define IDC_BUTTON_MAT_SAVE             1299
#define IDC_CHECK_USECOLOR1             1299
#define IDC_CHECK_USECOLOR2             1300
#define IDD_DLG_EFF_CLONEBLUR           25828
#define IDD_DLG_EFF_DUST                25829
#define IDC_FO_COLOR_VALUE              25830
#define IDD_DLG_EFF_SHOCK               25830
#define IDC_FO_COLOR_CUSTOM             25831
#define IDD_DLG_EFF_ATTRI               25831
#define IDC_FO_BUTTON_PREVIEW           25832
#define IDD_DLG_EFF_ARROW               25832
#define IDC_FO_SELECTCOLOR              25833
#define IDD_DLG_EFF_SPECULAR            25833
#define IDC_FO_COLOR_HEX_VALUE          25834
#define IDD_DLG_EFF_LEVEL               25834
#define IDD_DLG_EFF_EMIT                25835
#define IDD_DLG_EFF_ALPHA               25836
#define IDD_DLG_EFF_NEON                25837
#define IDD_DLG_EFF_MARK                25838
#define IDD_DLG_EFF_NOALPHA             25839
#define IDD_DLG_EFF_REFLECTION2         25840
#define IDD_DLG_EFF_AMBIENT             25841
#define IDD_DLG_EFF_DOT3                25842
#define IDD_DLG_EFF_MULTITEX            25843
#define IDD_DLG_EFF_GHOSTING            25844
#define IDD_DLG_EFF_SPECULAR2           25845
#define IDD_DLG_EFF_TOON                25846
#define IDD_DLG_EFF_TEXDIFF             25847
#define IDD_DLG_EFF_PARTICLE            25848
#define IDD_DLG_EFF_BONEPOS             25849
#define IDD_DLG_EFF_BONELIST            25850
#define IDD_DLG_EFF_USERCOLOR           25851
#define IDD_DLG_EFF_NORMALMAP           25852
#define IDD_DLG_EFF_LINE2BONE           25853
#define IDD_DLG_EFF_AROUND              25854
#define IDD_DLG_EFF_OVERLAY             25855
#define IDD_DLG_EFF_SPLINESINGLE        25856
#define IDD_DLG_EFF_VISUALMATERIAL      25857
#define IDC_FO_COLORS                   26516
#define ID_VIEW_EDITBAR                 32771
#define ID_RENDEROPTIONS_RENDERTRACE    32772
#define ID_COLLISIONDETECT_TYPE1        32773
#define ID_COLLISIONDETECT_TYPE2        32774
#define ID_COLLISIONDETECT_TYPE3        32775
#define ID_RENDEROPTIONS_RENDERSKELETON 32776
#define ID_RENDEROPTIONS_RENDERPLANE    32777
#define ID_RENDEROPTIONS_RENDERMODEL    32778
#define ID_FILE_OPENRAN2CPS             32779
#define ID_CNDEV                        32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1300
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
